version: 1.0.{build}
image: Ubuntu
init:
- sh: sudo apt-get -qq -y update > /dev/null && sudo apt-get -qq -y install libvulkan-dev > /dev/null && mkdir ../installer && curl -sSf https://cmake.org/files/v3.12/cmake-3.12.1-Linux-x86_64.sh > ../installer/cmake.sh && chmod a+x ../installer/cmake.sh && ../installer/cmake.sh --skip-license
clone_script:
- sh: rm -rf ./* && git clone https://github.com/JohnHolmesII/Triangle-2-Electric-Boogaloo.git . && git submodule update --init
build_script:
- sh: cmake . && chmod a+x build.sh && ./build.sh
