version: 1.0.{build}
image: Ubuntu1804
install:
- sh: git submodule -q update --init --recursive
init:
- sh: |
    sudo apt-get -qq update
    sudo apt-get -qq install libvulkan-dev libxi-dev libxrandr-dev libxinerama-dev libxcursor-dev libgl1-mesa-dev
build_script:
- sh: sh ./build.sh
